# Generated by Django 3.0.5 on 2020-04-22 04:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', django_mysql.models.JSONField(default=list)),
                ('intensity', django_mysql.models.JSONField(default=list)),
                ('reflectance', django_mysql.models.JSONField(default=list)),
                ('absorbance', django_mysql.models.JSONField(default=list)),
                ('config_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('product_serial', models.TextField()),
                ('img', models.ImageField(upload_to='pic/%Y%m%D')),
                ('label', models.IntegerField()),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', django_mysql.models.JSONField(default=list)),
                ('intensity', django_mysql.models.JSONField(default=list)),
                ('reflectance', django_mysql.models.JSONField(default=list)),
                ('absorbance', django_mysql.models.JSONField(default=list)),
                ('config_id', models.IntegerField()),
                ('device_serial', models.TextField()),
                ('product_serial', models.TextField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
