# Generated by Django 3.0.5 on 2020-04-13 12:24

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wavelength', django_mysql.models.JSONField(default=dict)),
                ('Intensity', django_mysql.models.JSONField(default=dict)),
                ('Reflectance', django_mysql.models.JSONField(default=dict)),
                ('Absorbance', django_mysql.models.JSONField(default=dict)),
                ('Config_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
                ('img_path', models.ImageField(upload_to='pic/%Y%m%D')),
            ],
        ),
    ]
