# Generated by Django 3.0.5 on 2020-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img_path',
            field=models.ImageField(upload_to='%Y%m%D'),
        ),
    ]
