# Generated by Django 3.0.5 on 2020-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200415_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img_path',
            field=models.ImageField(upload_to='pic/%Y%m%D'),
        ),
    ]
