# Generated by Django 3.0.5 on 2020-04-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200424_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='label',
            new_name='level',
        ),
    ]
