# Generated by Django 3.0.5 on 2020-04-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200415_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Absorbance',
            new_name='absorbance',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Config_id',
            new_name='config_id',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Intensity',
            new_name='intensity',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Reflectance',
            new_name='reflectance',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Wavelength',
            new_name='wavelength',
        ),
    ]
