# Generated by Django 3.0.5 on 2020-04-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.IntegerField()),
                ('start_wave', models.IntegerField()),
                ('end_wave', models.IntegerField()),
                ('wave_width', models.FloatField()),
                ('num_repeat', models.IntegerField()),
                ('exposure_time', models.FloatField()),
                ('num_point', models.IntegerField()),
            ],
        ),
    ]
