# Generated by Django 3.0.5 on 2020-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scantype', models.IntegerField()),
                ('Start_wave', models.IntegerField()),
                ('End_wave', models.IntegerField()),
                ('Wave_width', models.FloatField()),
                ('Num_repeat', models.IntegerField()),
                ('Exposure_time', models.FloatField()),
                ('Num_point', models.IntegerField()),
            ],
        ),
    ]
