# Generated by Django 3.0.5 on 2020-04-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='End_wave',
            new_name='end_wave',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Exposure_time',
            new_name='exposure_time',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Num_point',
            new_name='num_point',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Num_repeat',
            new_name='num_repeat',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Scantype',
            new_name='scan_type',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Start_wave',
            new_name='start_wave',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='Wave_width',
            new_name='wave_width',
        ),
    ]
